### ISSUE TITLE
Python binding of std::filesystem::path

### ISSUE THREAD

**Issue by MicheleCancilla** [deephealthproject/pyecvl#12]
I tried to access the `location_` class variable of `Sample`, which is a ` std::vector<std::filesystem::path>`, but I got this error:
> {TypeError}Unable to convert function return value to a Python type! The signature was
	(self: pyecvl._core.ecvl.Sample) -> std::filesystem::__cxx11::path
Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>, <pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic conversions are optional and require extra headers to be included when compiling your pybind11 module.

**Comment by simleo** [comment]
Fixed in #13.
