### ISSUE TITLE
Configure ecvl submodule for shallow clone

### ISSUE THREAD

**Issue by ilveroluca** [deephealthproject/pyecvl#6]
The ECVL history is quite heavy.  When cloning pyecvl, we don't need to the whole ecvl history, so we should do a shallow clone.

Apparently since git 2.1 you can [configure specific submodules to be cloned without history](https://stackoverflow.com/a/38895397)

```
git config -f .gitmodules submodule.<name>.shallow true
```

We should do this.

**Comment by simleo** [comment]
I've done some testing (see commits 10f1938c037f8b65888d36b128ff0133012c5ca8 to c4c77c3c61d5990f55f668ba52f5ad61d5cb48df) and it looks like it either has no effect or causes errors of type `Server does not allow request for unadvertised object`. See https://stackoverflow.com/questions/2144406/how-to-make-shallow-git-submodules/47374702#47374702 for more info. Better avoid this change for now, maybe they will clear things up in future git versions.
